# TASCA4

## NIVELL 1

### *Exercici 1*

+ Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
import numpy as np

In [2]:
from numpy import random

In [3]:
from statistics import mode

+ *Primer s'ha de crear l'array*

In [4]:
arr = np.random.randint(1, 20, 15)

In [5]:
arr

array([ 8,  1,  9, 16, 18, 14, 17, 13,  1, 10,  7, 13, 15, 13, 17])

In [6]:
def statistics_basics(arr):
    if arr.ndim > 1:
        print('Error: L\'array té mes d\'una dimensió')
    else:
        arr = np.sort(arr)
        print('The mean of the array is {}'.format(np.mean(arr))) 
        print('The median of the array is {}'.format(np.median(arr)))
        print('The mode of the array is {}'.format(mode(arr)))
        print('The variance of the array is {}'.format(arr.var()))
        print('The standard deviation of the array is {}'.format(arr.std()))

In [7]:
statistics_basics(arr)

The mean of the array is 11.466666666666667
The median of the array is 13.0
The mode of the array is 13
The variance of the array is 27.315555555555548
The standard deviation of the array is 5.226428566005236


### *Exercici 2*

+ Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [8]:
from random import randint

In [9]:
def matrix_generator():
    y = int(input('Tria un numero del 1 al 10: '))
    matriu_nxn = np.random.randint(1, 101, size = (y, y))
    return matriu_nxn

In [10]:
matrix_generator()

Tria un numero del 1 al 10: 4


array([[51, 79, 84, 59],
       [64, 79, 82, 54],
       [73, 88, 80, 31],
       [29, 45, 69, 10]])

### *Exercici 3*

+ Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.


+ *OPCIÓ 1 - amb inputs i generació de matriu amb np.random.randint i paràmetres necessaris*

In [11]:
def matriu_generador():
    x = int(input('Tria un numero del 1 al 10: '))
    y = int(input('Tria un numero del 1 al 10: '))
    matriu_nxy = np.random.randint(1, 101, size = (x, y))
    print('Els totals per fila són {}'.format(np.sum(matriu_nxy, axis=1)))
    print('Els totals per columna són {}'.format(np.sum(matriu_nxy, axis=0)))
    return matriu_nxy
  

In [12]:
matriu_generador()

Tria un numero del 1 al 10: 4
Tria un numero del 1 al 10: 5
Els totals per fila són [132 308 326 232]
Els totals per columna són [182 191 276 189 160]


array([[19, 62, 20, 11, 20],
       [82,  4, 86, 96, 40],
       [39, 80, 96, 38, 73],
       [42, 45, 74, 44, 27]])

+ *OPCIÓ 2 - amb un loop for anidat que ompli una array buida declarada inicialment (matriu) que es va omplint de files*

In [13]:
def omplir_matriu(x, y):
    matriu = []
    for r in range(x):
        fila = []
        for c in range(y):
            fila.append(random.randint(1, 101))
        matriu.append(fila)
    print('Els totals per fila són {}'.format(np.sum(matriu, axis=1)))
    print('Els totals per columna són {}'.format(np.sum(matriu, axis=0)))
    return matriu

In [14]:
omplir_matriu(4,5)

Els totals per fila són [264 225 353 177]
Els totals per columna són [248 111 190 280 190]


[[45, 21, 49, 73, 76],
 [55, 14, 40, 93, 23],
 [100, 14, 75, 97, 67],
 [48, 62, 26, 17, 24]]

### *EXERCICI 4*

+ Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació

+ Per fer l'exercici m'invento 2 arrays - la primera amb edats de nens i nenes d'una família i la segona amb les alçades 
   corresponents a cadascun dels infants.
   
   Un cop generades veurem quin és l'índex de correlació ("r"), que ens informa del comportament d'una de les variables en        relació a l'altra; amb una que trobarà tots els components de la fórmula de l'índex de correlació per poder aplicar-la*
   
   FORMULA : r = Sxy / Sx * Sy on : Sxy = (Sumatori Xi * Yi / N - mitjana x) * mitjana y
                                Sx = 
                                Sy = 
   És a dir, l'índex de correlació entre les variables x, y és el cocient entre la covariança d'x,y;  i el producte de les    
   respectives desviacions típiques.
   
   Podem trobar:
   + una relació directa, que significa que quan una variable creix o decreix l'altra també ho fa (amb r > 0) 
   + una relació inversa, que significa que quan una variable creix o decreix l'altra fa el contrari (amb r < 0) 
   
   Quan més "a l'hora" es comportin les dues variables, més a prop de 1 (cas relació directa) o de -1 (cas relació inversa) 
   serà "r"

In [15]:
edats = np.array([2, 5, 10, 13, 16])
alçades = np.array([0.70, 0.85, 1.40, 1.60, 1.75])

In [16]:
def index_corr(edats, alçades):
    productes = np.multiply(edats, alçades)
    print(productes)
    suma_productes = np.sum(productes)
    print(suma_productes)
    edats_mean = np.sum(edats) / len(edats)
    alçades_mean = np.sum(alçades) / len(alçades)
    covar = (suma_productes / len(edats)) - (edats_mean*alçades_mean)
    print(covar)
    print(edats_mean, alçades_mean)
    std_edats = ((np.sum(edats**2) / len(edats)) - edats_mean**2)** 0.5
    print(std_edats)
    std_alçades = ((np.sum(alçades**2) / len(alçades)) - alçades_mean**2)** 0.5
    print(std_alçades)
    result = covar/(std_edats*std_alçades)
    return result
    

In [17]:
print('index de correlació entre edats i alçades és : {}'.format(index_corr(edats, alçades)))

[ 1.4   4.25 14.   20.8  28.  ]
68.45
2.0980000000000025
9.2 1.26
5.114684741017769
0.41400483088968876
index de correlació entre edats i alçades és : 0.9907890660431076
